version: "3.5"

networks:
  localdev:
    name: localdev

services:
  unecont:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-server
    environment:
      "ASPNETCORE_ENVIRONMENT": Development
      "ConnectionStrings__DefaultConnection": "Server=YOU_IPV4,1400;Database=unecont;User Id=sa;Password=YouPassword123;MultipleActiveResultSets=true;TrustServerCertificate=True"
    ports:
      - "5000:8080" 
    networks:
      - localdev

  db-server:
    image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
    container_name: db-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YouPassword123"
    ports:
      - "1400:1433"
    networks:
      - localdev
